blog/blog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    url(r'^blog/', include('blogapp.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

blog/blogapp/urls.py
from django.conf.urls import patterns, include, url

from . import views

app_name = 'blogapp'
urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^update/$', views.update, name="update"),
    url(r'^delete/$', views.delete, name="delete"),
    url(r'^search/$', views.search, name="search"),
)

blog/blogapp/models.py
from django.db import models

# Create your models here.
from mongoengine import *
from blog.settings import DBNAME

connect(DBNAME)

class Recipecollection(Document):
	title = StringField(max_length=100, required=True)
	domain = StringField(max_length=100, required=True)
	itemurl = URLField()
	categoriestags = ListField(StringField(max_length=100))
	author = StringField(max_length=100, required=True)
	authorlink = URLField()
	serves = StringField(max_length=50, required=True)
	imglink = URLField()
	ingredients = StringField()

blog/blogapp/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from models import Recipecollection
import datetime
from django.http import HttpResponse
import json
from django.views.decorators.csrf import csrf_exempt


def index(request):
    if request.method == 'POST':
       # save new post
      domain = request.POST['domain']
      post = Recipecollection(domain=domain)
      post.title = request.POST['title']
      post.itemurl = request.POST['itemurl']
      post.categoriestags = [cate.encode("ascii", "ignore").strip() for cate in request.POST['categoriestags'].split(",")]
      post.author = request.POST["author"]
      post.authorlink = request.POST["authorlink"]
      post.serves = request.POST["serves"]
      post.imglink = request.POST["imglink"]
      post.ingredients = request.POST["ingredients"]
      post.save()

    # Get all posts from DB
    posts = Recipecollection.objects 
    return render_to_response('blogapp/index.html', {'Posts': posts},
                              context_instance=RequestContext(request))


def update(request):
    id = eval("request." + request.method + "['id']")
    post = Recipecollection.objects(id=id)[0]
    
    if request.method == 'POST':
        # update field values and save to mongo
        post.domain = request.POST['domain']
        post.title = request.POST['title']
        post.itemurl = request.POST['itemurl']
        post.categoriestags = [cate.encode("ascii", "ignore").strip() for cate in request.POST['categoriestags'].split(",")]
        post.author = request.POST["author"]
        post.authorlink = request.POST["authorlink"]
        post.serves = request.POST["serves"]
        post.imglink = request.POST["imglink"]
        post.ingredients = request.POST["ingredients"]
        post.save()
        template = 'blogapp/index.html'
        params = {'Posts': Recipecollection.objects} 

    elif request.method == 'GET':
        template = 'blogapp/update.html'
        params = {'post':post}
   
    return render_to_response(template, params, context_instance=RequestContext(request))
                              

def delete(request):
    id = eval("request." + request.method + "['id']")

    if request.method == 'POST':
        post = Recipecollection.objects(id=id)[0]
        post.delete() 
        template = 'blogapp/index.html'
        params = {'Posts': Recipecollection.objects} 
    elif request.method == 'GET':
        template = 'blogapp/delete.html'
        params = { 'id': id } 

    return render_to_response(template, params, context_instance=RequestContext(request))


@csrf_exempt
def search(request):
  term = request.POST.get("term", "")
  query = {"$or":[{ "title": { "$regex": r'^%s.*'%(term), "$options": "si" }}, {"author": { "$regex": r'^%s.*'%(term), "$options": "si" } }]}
  r_record = Recipecollection.objects(__raw__=query)
  params = {'Posts': r_record} 
  template = "blogapp/blog_search_temp.html"
  return render_to_response(template, params, context_instance=RequestContext(request))

blog/blogapp/templates/blogapp/blog_search_temp.html
    {% for post in Posts %}
      <h2>Title:- {{ post.title }} </h2>
      <p>Domain:- {{ post.domain }} </p>
      <p>Item Url:- {{ post.itemurl }} </p>
      <p>Categories Tags:- 
      {% for cate in post.categoriestags %}
          {{cate}}, 
      {% endfor %}
      </p>

      <p>Author:- {{ post.author }}</p>
      <p>Author Link:- {{ post.authorlink }} </p>
      <!-- <p>Image link:- <img src="{{ post.imglink }}" alt="Smiley face" height="200" width="400"> </p> -->
      <p> serves {{post.serves}}</p>
      <p>Ingredients:- 
          {{post.ingredients}}
      </p>


      <form method="get" action="{% url 'blogapp:update' %}">
        <input type="hidden" name="id" value="{{ post.id }}">
        <input type="hidden" name="title" value="{{ post.title }}">
        <input type="hidden" name="domain" value="{{ post.domain }}">
        <input type="hidden" name="itemurl" value="{{ post.itemurl }}">
        <input type="hidden" name="categoriestags" value="{{ post.categoriestags }}">
        <input type="hidden" name="author" value="{{ post.author }}">
        <input type="hidden" name="authorlink" value="{{ post.authorlink }}">
        <input type="hidden" name="imglink" value="{{ post.imglink }}">
        <input type="hidden" name="serves" value="{{ post.serves }}">
        <input type="hidden" name="ingredients" value="{{ post.ingredients }}">
        <input type="submit" name="" value="update">
      </form>
      <form method="get" action="{% url 'blogapp:delete' %}">
        <input type="hidden" name="id" value="{{post.id}}">
        <input type="submit" value="delete">
      </form>
    {% endfor %}

blog/blogapp/templates/blogapp/delete.html
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog.css" rel="stylesheet" type="text/css">  
  </head> 
  <body>
    <h1>Blongo - Delete Entry</h1>
    <form method="post" action="{% url 'blogapp:delete' %}">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{id}}">
      <p>Are you sure you want to delete this post?</p>
      <input type="submit" value="Delete">
    </form>
  </body>
</html>

blog/blogapp/templates/blogapp/index.html
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog.css" rel="stylesheet" type="text/css">
    <link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <style>
         #project-label {
            display: block;
            font-weight: bold;
            margin-bottom: 1em;
         }
         #project-icon {
            float: left;
            height: 32px;
            width: 32px;
         }
         #project-description {
            margin: 0;
            padding: 0;
         }
      </style>


      <script>
        $(document).ready(function(){
          $( "#project" ).keyup(function() {
            value = $(this).val();
            $.post("{% url 'blogapp:search' %}", 
              {
                term:value, 
                csrftoken:"{% csrf_token %}"
              },
              function(data, status){
                $("#entrycycle").empty();
                $( "#entrycycle" ).append( data );
              }
            )
          });

        });
      </script>


  </head> 
  <body>
    <h1>Blogs</h1>
    <center>
         <input id="project" placeholder="Search for a Recipe or Chef" value="">
         <input type="hidden" id="project-id">
         <p id="project-description"></p>
    </center> 

    <br /><br /><br />

     <center>Add Blog</center> 
     <center>
    <form method="post" action="{% url 'blogapp:index' %}">
      {% csrf_token %}
      <ul>
        <li>
          <input type="url" name="domain" placeholder="Domain" required>
        </li>
        <li>
          <input type="text" name="title" placeholder="Title" required>
        </li>
        <li>
          <input type="url" name="itemurl" placeholder="Item Url" required>
        </li>
        <li>
          <input type="text" name="categoriestags" placeholder="Categories Tags" required>
        </li>
        <li>
          <input type="text" name="author" placeholder="Author" required>
        </li>
        <li>
          <input type="url" name="authorlink" placeholder="Author Link">
        </li>
         <li>
          <input type="text" name="serves" placeholder="Serves">
        </li>
        <li>
          <input type="url" name="imglink" placeholder="Imgage Link">
        </li>
        <li>
          <textarea name="ingredients" placeholder="Ingredients: comma separated ex:- potato 32g, tomato 30g" rows=5 cols=50 required>
          </textarea>
        </li>
        <li>
          <input type="submit" value="Add Post">
        </li>
      </ul>
    </form>
    </center> 
<!-- Cycle through entries -->
  <div id="entrycycle">
    {% include "blogapp/blog_search_temp.html" %}
    </div>
  </body>
</html>

blog/blogapp/templates/blogapp/update.html
<!DOCTYPE html>
<html>
  <head>
    <link href="{{STATIC_URL}}blog.css" rel="stylesheet" type="text/css">
  </head> 
  <body>
    <h1>Blongo - Update Entry</h1>
    <form method="post" action="{% url 'blogapp:update' %}">
      {% csrf_token %}
      <ul>
      <li><input type="hidden" name="id" value="{{post.id}}"></li>
        <li>
          <input type="url" name="domain" placeholder="Domain" required>
        </li>
        <li>
          <input type="text" name="title" placeholder="Title" required>
        </li>
        <li>
          <input type="url" name="itemurl" placeholder="Item Url" required>
        </li>
        <li>
          <input type="text" name="categoriestags" placeholder="Categories Tags" required>
        </li>
        <li>
          <input type="text" name="author" placeholder="Author" required>
        </li>
        <li>
          <input type="url" name="authorlink" placeholder="Author Link">
        </li>
         <li>
          <input type="text" name="serves" placeholder="Serves">
        </li>
        <li>
          <input type="url" name="imglink" placeholder="Imgage Link">
        </li>
        <li>
          <textarea name="ingredients" placeholder="Ingredients: comma separated ex:- potato 32g, tomato 30g" rows=5 cols=50 required>
          </textarea>
        </li>
        <li>
          <input type="submit" value="Save Changes">
        </li>
      </ul>

  </body>
</html>